const PROJECTS = [
  {
    id: "rubakha-edinovlastie",
    ru: { title: "По протоколу. Верх Рубаха от бренда EDINOVLASTIE", desc: "" },
    en: { title: "Shirt by EDINOVLASTIE — «По протоколу. Верх»", desc: "" },
    zh: { title: "EDINOVLASTIE品牌衬衫 — «По протоколу. Верх»", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/01.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/02.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/03.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/04.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/05.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/06.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/07.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/08.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/09.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/010.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/011.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/012.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/013.jpg",
    "portfolio/img/«По протоколу. Верх» Рубаха от бренда EDINOVLASTIE/014.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "belye-dvoechka",
    ru: { title: "Белье ДВОЕЧКА", desc: "" },
    en: { title: "Lingerie Set «ДВОЕЧКА»", desc: "" },
    zh: { title: "内衣套装 «ДВОЕЧКА»", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Белье _ДВОЕЧКА_/01.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/02.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/03.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/04.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/05.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/06.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/07.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/08.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/09.jpg",
    "portfolio/img/Белье _ДВОЕЧКА_/010.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "blazer-transformer-edinovlastie",
    ru: { title: "Блейзер-трансформер от бренда EDINOVLASTIE", desc: "" },
    en: { title: "Transformer Blazer by EDINOVLASTIE", desc: "" },
    zh: { title: "EDINOVLASTIE品牌变形西装外套", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/01.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/02.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/03.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/04.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/05.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/06.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/07.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/08.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/09.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/010.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/011.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/012.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/013.jpg",
    "portfolio/img/Блейзер-трансформер от бренда EDINOVLASTIE/014.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "bryuki-milano",
    ru: { title: "Брюки МИЛАНО", desc: "" },
    en: { title: "Trousers MILANO", desc: "" },
    zh: { title: "MILANO裤子", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Брюки МИЛАНО/01.webp",
    "portfolio/img/Брюки МИЛАНО/02.webp",
    "portfolio/img/Брюки МИЛАНО/03.webp",
    "portfolio/img/Брюки МИЛАНО/04.webp",
    "portfolio/img/Брюки МИЛАНО/05.webp",
    "portfolio/img/Брюки МИЛАНО/06.webp",
    "portfolio/img/Брюки МИЛАНО/07.webp",
    "portfolio/img/Брюки МИЛАНО/08.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "bryuki-edinovlastie",
    ru: { title: "Брюки от бренда EDINOVLASTIE", desc: "" },
    en: { title: "Trousers by EDINOVLASTIE", desc: "" },
    zh: { title: "EDINOVLASTIE品牌裤子", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Брюки от бренда EDINOVLASTIE/01.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/02.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/03.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/04.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/05.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/06.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/07.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/08.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/09.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/010.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/011.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/012.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/013.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/014.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/015.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/016.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/017.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/018.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/019.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/020.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/021.jpg",
    "portfolio/img/Брюки от бренда EDINOVLASTIE/022.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "zhilet-franky-bar",
    ru: { title: "Жилет Franky Bar", desc: "" },
    en: { title: "Vest Franky Bar", desc: "" },
    zh: { title: "Franky Bar马甲", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Жилет Franky Bar/01.jpg",
    "portfolio/img/Жилет Franky Bar/02.jpg",
    "portfolio/img/Жилет Franky Bar/03.jpg",
    "portfolio/img/Жилет Franky Bar/04.jpg",
    "portfolio/img/Жилет Franky Bar/05.jpg",
    "portfolio/img/Жилет Franky Bar/06.jpg",
    "portfolio/img/Жилет Franky Bar/07.jpg",
    "portfolio/img/Жилет Franky Bar/08.jpg",
    "portfolio/img/Жилет Franky Bar/09.jpg",
    "portfolio/img/Жилет Franky Bar/010.jpg",
    "portfolio/img/Жилет Franky Bar/011.jpg",
    "portfolio/img/Жилет Franky Bar/012.jpg",
    "portfolio/img/Жилет Franky Bar/013.jpg",
    "portfolio/img/Жилет Franky Bar/014.jpg",
    "portfolio/img/Жилет Franky Bar/015.jpg",
    "portfolio/img/Жилет Franky Bar/016.jpg",
    "portfolio/img/Жилет Franky Bar/017.jpg",
    "portfolio/img/Жилет Franky Bar/018.jpg",
    "portfolio/img/Жилет Franky Bar/019.jpg",
    "portfolio/img/Жилет Franky Bar/020.jpg",
    "portfolio/img/Жилет Franky Bar/021.jpg",
    "portfolio/img/Жилет Franky Bar/022.jpg",
    "portfolio/img/Жилет Franky Bar/023.jpg",
    "portfolio/img/Жилет Franky Bar/024.jpg",
    "portfolio/img/Жилет Franky Bar/025.jpg",
    "portfolio/img/Жилет Franky Bar/026.jpg",
    "portfolio/img/Жилет Franky Bar/027.jpg",
    "portfolio/img/Жилет Franky Bar/028.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "zhiletka-odnoplechy",
    ru: { title: "Жилетка костюмная на одно плечо с воланом", desc: "" },
    en: { title: "One-shoulder Suit Waistcoat with Ruffle", desc: "" },
    zh: { title: "单肩荷叶边西装马甲", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Жилетка костюмная на одно плечо с воланом/01.webp",
    "portfolio/img/Жилетка костюмная на одно плечо с воланом/02.webp",
    "portfolio/img/Жилетка костюмная на одно плечо с воланом/03.webp",
    "portfolio/img/Жилетка костюмная на одно плечо с воланом/04.webp",
    "portfolio/img/Жилетка костюмная на одно плечо с воланом/05.webp",
    "portfolio/img/Жилетка костюмная на одно плечо с воланом/06.webp",
    "portfolio/img/Жилетка костюмная на одно плечо с воланом/07.webp",
    "portfolio/img/Жилетка костюмная на одно плечо с воланом/08.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "zipka",
    ru: { title: "Зипка", desc: "" },
    en: { title: "Zip-up Hoodie", desc: "" },
    zh: { title: "拉链卫衣", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Зипка/01.jpg",
    "portfolio/img/Зипка/02.jpg",
    "portfolio/img/Зипка/03.jpg",
    "portfolio/img/Зипка/04.jpg",
    "portfolio/img/Зипка/05.jpg",
    "portfolio/img/Зипка/06.jpg",
    "portfolio/img/Зипка/07.jpg",
    "portfolio/img/Зипка/08.jpg",
    "portfolio/img/Зипка/09.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "kardigan-edinovlastie",
    ru: { title: "Кардиган от бренда EDINOVLASTIE", desc: "" },
    en: { title: "Cardigan by EDINOVLASTIE", desc: "" },
    zh: { title: "EDINOVLASTIE品牌针织开衫", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/01.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/02.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/03.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/04.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/05.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/06.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/07.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/08.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/09.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/010.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/011.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/012.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/013.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/014.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/015.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/016.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/017.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/018.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/019.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/020.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/021.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/022.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/023.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/024.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/025.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/026.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/027.jpg",
    "portfolio/img/Кардиган от бренда EDINOVLASTIE/028.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "kombinezon-archi",
    ru: { title: "Комбинезон ARCHI", desc: "" },
    en: { title: "Jumpsuit ARCHI", desc: "" },
    zh: { title: "ARCHI连体裤", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Комбинезон _ARCHI/01.jpg",
    "portfolio/img/Комбинезон _ARCHI/02.jpg",
    "portfolio/img/Комбинезон _ARCHI/03.jpg",
    "portfolio/img/Комбинезон _ARCHI/04.jpg",
    "portfolio/img/Комбинезон _ARCHI/05.jpg",
    "portfolio/img/Комбинезон _ARCHI/06.jpg",
    "portfolio/img/Комбинезон _ARCHI/07.jpg",
    "portfolio/img/Комбинезон _ARCHI/08.jpg",
    "portfolio/img/Комбинезон _ARCHI/09.jpg",
    "portfolio/img/Комбинезон _ARCHI/010.jpg",
    "portfolio/img/Комбинезон _ARCHI/011.jpg",
    "portfolio/img/Комбинезон _ARCHI/012.jpg",
    "portfolio/img/Комбинезон _ARCHI/013.jpg",
    "portfolio/img/Комбинезон _ARCHI/014.jpg",
    "portfolio/img/Комбинезон _ARCHI/015.jpg",
    "portfolio/img/Комбинезон _ARCHI/016.jpg",
    "portfolio/img/Комбинезон _ARCHI/017.jpg",
    "portfolio/img/Комбинезон _ARCHI/018.jpg",
    "portfolio/img/Комбинезон _ARCHI/019.jpg",
    "portfolio/img/Комбинезон _ARCHI/020.jpg",
    "portfolio/img/Комбинезон _ARCHI/021.jpg",
    "portfolio/img/Комбинезон _ARCHI/022.jpg",
    "portfolio/img/Комбинезон _ARCHI/023.jpg",
    "portfolio/img/Комбинезон _ARCHI/024.jpg",
    "portfolio/img/Комбинезон _ARCHI/025.jpg",
    "portfolio/img/Комбинезон _ARCHI/026.jpg",
    "portfolio/img/Комбинезон _ARCHI/027.jpg",
    "portfolio/img/Комбинезон _ARCHI/028.jpg",
    "portfolio/img/Комбинезон _ARCHI/057.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "kostyum-lanitissimo",
    ru: { title: "Костюм Lanitissimo", desc: "" },
    en: { title: "Suit Lanitissimo", desc: "" },
    zh: { title: "Lanitissimo套装", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Костюм Lanitissimo/01.webp",
    "portfolio/img/Костюм Lanitissimo/02.webp",
    "portfolio/img/Костюм Lanitissimo/03.webp",
    "portfolio/img/Костюм Lanitissimo/04.webp",
    "portfolio/img/Костюм Lanitissimo/05.webp",
    "portfolio/img/Костюм Lanitissimo/06.webp",
    "portfolio/img/Костюм Lanitissimo/07.webp",
    "portfolio/img/Костюм Lanitissimo/08.webp",
    "portfolio/img/Костюм Lanitissimo/09.webp",
    "portfolio/img/Костюм Lanitissimo/010.webp",
    "portfolio/img/Костюм Lanitissimo/011.webp",
    "portfolio/img/Костюм Lanitissimo/012.webp",
    "portfolio/img/Костюм Lanitissimo/013.webp",
    "portfolio/img/Костюм Lanitissimo/014.webp",
    "portfolio/img/Костюм Lanitissimo/015.webp",
    "portfolio/img/Костюм Lanitissimo/016.webp",
    "portfolio/img/Костюм Lanitissimo/017.webp",
    "portfolio/img/Костюм Lanitissimo/018.webp",
    "portfolio/img/Костюм Lanitissimo/019.webp",
    "portfolio/img/Костюм Lanitissimo/020.webp",
    "portfolio/img/Костюм Lanitissimo/021.webp",
    "portfolio/img/Костюм Lanitissimo/022.webp",
    "portfolio/img/Костюм Lanitissimo/023.webp",
    "portfolio/img/Костюм Lanitissimo/024.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "kostyum-vinkult",
    ru: { title: "Костюм Vinkult", desc: "" },
    en: { title: "Suit Vinkult", desc: "" },
    zh: { title: "Vinkult套装", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Костюм Vinkult/01.jpg",
    "portfolio/img/Костюм Vinkult/02.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "kostyum-friends",
    ru: { title: "Костюм Friends", desc: "" },
    en: { title: "Suit «Friends»", desc: "" },
    zh: { title: "«Friends»套装", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Костюм _Friends_/01.jpg",
    "portfolio/img/Костюм _Friends_/02.jpg",
    "portfolio/img/Костюм _Friends_/03.jpg",
    "portfolio/img/Костюм _Friends_/04.jpg",
    "portfolio/img/Костюм _Friends_/05.jpg",
    "portfolio/img/Костюм _Friends_/06.jpg",
    "portfolio/img/Костюм _Friends_/07.jpg",
    "portfolio/img/Костюм _Friends_/08.jpg",
    "portfolio/img/Костюм _Friends_/09.jpg",
    "portfolio/img/Костюм _Friends_/010.jpg",
    "portfolio/img/Костюм _Friends_/011.jpg",
    "portfolio/img/Костюм _Friends_/012.jpg",
    "portfolio/img/Костюм _Friends_/013.jpg",
    "portfolio/img/Костюм _Friends_/014.jpg",
    "portfolio/img/Костюм _Friends_/015.jpg",
    "portfolio/img/Костюм _Friends_/016.jpg",
    "portfolio/img/Костюм _Friends_/017.jpg",
    "portfolio/img/Костюм _Friends_/018.jpg",
    "portfolio/img/Костюм _Friends_/019.jpg",
    "portfolio/img/Костюм _Friends_/020.jpg",
    "portfolio/img/Костюм _Friends_/021.jpg",
    "portfolio/img/Костюм _Friends_/022.jpg",
    "portfolio/img/Костюм _Friends_/023.jpg",
    "portfolio/img/Костюм _Friends_/024.jpg",
    "portfolio/img/Костюм _Friends_/025.jpg",
    "portfolio/img/Костюм _Friends_/026.jpg",
    "portfolio/img/Костюм _Friends_/027.jpg",
    "portfolio/img/Костюм _Friends_/028.jpg",
    "portfolio/img/Костюм _Friends_/029.jpg",
    "portfolio/img/Костюм _Friends_/030.jpg",
    "portfolio/img/Костюм _Friends_/031.jpg",
    "portfolio/img/Костюм _Friends_/032.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "kostyum-vector",
    ru: { title: "Костюм Vector", desc: "" },
    en: { title: "Suit «Vector»", desc: "" },
    zh: { title: "«Vector»套装", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Костюм _Vector_/01.jpg",
    "portfolio/img/Костюм _Vector_/02.jpg",
    "portfolio/img/Костюм _Vector_/03.jpg",
    "portfolio/img/Костюм _Vector_/04.jpg",
    "portfolio/img/Костюм _Vector_/05.jpg",
    "portfolio/img/Костюм _Vector_/06.jpg",
    "portfolio/img/Костюм _Vector_/07.jpg",
    "portfolio/img/Костюм _Vector_/08.jpg",
    "portfolio/img/Костюм _Vector_/09.jpg",
    "portfolio/img/Костюм _Vector_/010.jpg",
    "portfolio/img/Костюм _Vector_/011.jpg",
    "portfolio/img/Костюм _Vector_/012.jpg",
    "portfolio/img/Костюм _Vector_/013.jpg",
    "portfolio/img/Костюм _Vector_/014.jpg",
    "portfolio/img/Костюм _Vector_/015.jpg",
    "portfolio/img/Костюм _Vector_/016.jpg",
    "portfolio/img/Костюм _Vector_/017.jpg",
    "portfolio/img/Костюм _Vector_/018.jpg",
    "portfolio/img/Костюм _Vector_/019.jpg",
    "portfolio/img/Костюм _Vector_/020.jpg",
    "portfolio/img/Костюм _Vector_/021.jpg",
    "portfolio/img/Костюм _Vector_/022.jpg",
    "portfolio/img/Костюм _Vector_/023.jpg",
    "portfolio/img/Костюм _Vector_/024.jpg",
    "portfolio/img/Костюм _Vector_/025.jpg",
    "portfolio/img/Костюм _Vector_/026.jpg",
    "portfolio/img/Костюм _Vector_/027.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "лонгслив-детский",
    ru: { title: "Лонгслив детский", desc: "" },
    en: { title: "Лонгслив детский", desc: "" },
    zh: { title: "Лонгслив детский", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Лонгслив детский/01.webp",
    "portfolio/img/Лонгслив детский/02.webp",
    "portfolio/img/Лонгслив детский/03.webp",
    "portfolio/img/Лонгслив детский/04.webp",
    "portfolio/img/Лонгслив детский/05.webp",
    "portfolio/img/Лонгслив детский/06.webp",
    "portfolio/img/Лонгслив детский/07.webp",
    "portfolio/img/Лонгслив детский/08.webp",
    "portfolio/img/Лонгслив детский/09.webp",
    "portfolio/img/Лонгслив детский/010.webp",
    "portfolio/img/Лонгслив детский/011.webp",
    "portfolio/img/Лонгслив детский/012.webp",
    "portfolio/img/Лонгслив детский/013.webp",
    "portfolio/img/Лонгслив детский/014.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "longsleeve-edinovlastie",
    ru: { title: "Лонгслив от бренда EDINOVLASTIE", desc: "" },
    en: { title: "Long-sleeve by EDINOVLASTIE", desc: "" },
    zh: { title: "EDINOVLASTIE品牌长袖上衣", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/01.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/02.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/03.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/04.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/05.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/06.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/07.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/08.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/09.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/010.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/011.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/012.jpg",
    "portfolio/img/Лонгслив от бренда EDINOVLASTIE/013.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "nabor-topikov-print",
    ru: { title: "Набор топиков с принтом", desc: "" },
    en: { title: "Printed Tops Set", desc: "" },
    zh: { title: "印花上衣套装", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Набор топиков с принтом/01.webp",
    "portfolio/img/Набор топиков с принтом/02.webp",
    "portfolio/img/Набор топиков с принтом/03.webp",
    "portfolio/img/Набор топиков с принтом/04.webp",
    "portfolio/img/Набор топиков с принтом/05.webp",
    "portfolio/img/Набор топиков с принтом/06.webp",
    "portfolio/img/Набор топиков с принтом/07.webp",
    "portfolio/img/Набор топиков с принтом/08.webp",
    "portfolio/img/Набор топиков с принтом/09.webp",
    "portfolio/img/Набор топиков с принтом/010.webp",
    "portfolio/img/Набор топиков с принтом/011.webp",
    "portfolio/img/Набор топиков с принтом/012.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "nabor-topov-belye",
    ru: { title: "Набор топов бельевых", desc: "" },
    en: { title: "Lingerie Tops Set", desc: "" },
    zh: { title: "内衣背心套装", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Набор топов бельевых/01.webp",
    "portfolio/img/Набор топов бельевых/02.webp",
    "portfolio/img/Набор топов бельевых/03.webp",
    "portfolio/img/Набор топов бельевых/04.webp",
    "portfolio/img/Набор топов бельевых/05.webp",
    "portfolio/img/Набор топов бельевых/08.webp",
    "portfolio/img/Набор топов бельевых/010.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "platye-transformer-edinovlastie",
    ru: { title: "Платье-трансформер от бренда EDINOVLASTIE", desc: "" },
    en: { title: "Transformer Dress by EDINOVLASTIE", desc: "" },
    zh: { title: "EDINOVLASTIE品牌变形连衣裙", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/01.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/02.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/03.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/04.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/05.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/06.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/07.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/08.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/09.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/010.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/011.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/012.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/013.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/014.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/015.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/016.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/017.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/018.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/019.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/020.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/021.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/022.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/023.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/024.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/025.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/026.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/027.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/028.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/029.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/030.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/031.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/032.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/033.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/034.jpg",
    "portfolio/img/Платье-трансформер от бренда EDINOVLASTIE/035.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "polo-corto",
    ru: { title: "Поло CORTO", desc: "" },
    en: { title: "Polo CORTO", desc: "" },
    zh: { title: "CORTO Polo衫", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Поло CORTO/01.webp",
    "portfolio/img/Поло CORTO/02.webp",
    "portfolio/img/Поло CORTO/03.webp",
    "portfolio/img/Поло CORTO/04.webp",
    "portfolio/img/Поло CORTO/05.webp",
    "portfolio/img/Поло CORTO/06.webp",
    "portfolio/img/Поло CORTO/07.webp",
    "portfolio/img/Поло CORTO/08.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "rubashka-bellini",
    ru: { title: "Рубашка BELLINI", desc: "" },
    en: { title: "Shirt BELLINI", desc: "" },
    zh: { title: "BELLINI衬衫", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Рубашка BELLINI/01.webp",
    "portfolio/img/Рубашка BELLINI/02.webp",
    "portfolio/img/Рубашка BELLINI/03.webp",
    "portfolio/img/Рубашка BELLINI/04.webp",
    "portfolio/img/Рубашка BELLINI/05.webp",
    "portfolio/img/Рубашка BELLINI/06.webp",
    "portfolio/img/Рубашка BELLINI/07.webp",
    "portfolio/img/Рубашка BELLINI/08.webp",
    "portfolio/img/Рубашка BELLINI/09.webp",
    "portfolio/img/Рубашка BELLINI/010.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "rubashka-ristretto",
    ru: { title: "Рубашка RISTRETTO", desc: "" },
    en: { title: "Shirt RISTRETTO", desc: "" },
    zh: { title: "RISTRETTO衬衫", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Рубашка RISTRETTO/01.webp",
    "portfolio/img/Рубашка RISTRETTO/02.webp",
    "portfolio/img/Рубашка RISTRETTO/03.webp",
    "portfolio/img/Рубашка RISTRETTO/04.webp",
    "portfolio/img/Рубашка RISTRETTO/05.webp",
    "portfolio/img/Рубашка RISTRETTO/06.webp",
    "portfolio/img/Рубашка RISTRETTO/07.webp",
    "portfolio/img/Рубашка RISTRETTO/08.webp",
    "portfolio/img/Рубашка RISTRETTO/09.webp",
    "portfolio/img/Рубашка RISTRETTO/010.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "top",
    ru: { title: "Топ", desc: "" },
    en: { title: "Top", desc: "" },
    zh: { title: "上衣", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Топ/01.jpg",
    "portfolio/img/Топ/02.jpg",
    "portfolio/img/Топ/03.jpg",
    "portfolio/img/Топ/04.jpg",
    "portfolio/img/Топ/05.jpg",
    "portfolio/img/Топ/06.jpg",
    "portfolio/img/Топ/07.jpg",
    "portfolio/img/Топ/08.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "top-odnoplechy",
    ru: { title: "Топ на одно плечо", desc: "" },
    en: { title: "One-shoulder Top", desc: "" },
    zh: { title: "单肩上衣", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Топ на одно плечо/01.webp",
    "portfolio/img/Топ на одно плечо/02.webp",
    "portfolio/img/Топ на одно плечо/03.webp",
    "portfolio/img/Топ на одно плечо/04.webp",
    "portfolio/img/Топ на одно плечо/05.webp",
    "portfolio/img/Топ на одно плечо/06.webp",
    "portfolio/img/Топ на одно плечо/07.webp",
    "portfolio/img/Топ на одно плечо/08.webp",
    "portfolio/img/Топ на одно плечо/09.webp",
    "portfolio/img/Топ на одно плечо/010.webp",
    "portfolio/img/Топ на одно плечо/011.webp",
    "portfolio/img/Топ на одно плечо/012.webp",
    "portfolio/img/Топ на одно плечо/013.webp",
    "portfolio/img/Топ на одно плечо/014.webp",
    "portfolio/img/Топ на одно плечо/015.webp",
    "portfolio/img/Топ на одно плечо/016.webp",
    "portfolio/img/Топ на одно плечо/017.webp",
    "portfolio/img/Топ на одно плечо/018.webp",
    "portfolio/img/Топ на одно плечо/019.webp",
    "portfolio/img/Топ на одно плечо/020.webp",
    "portfolio/img/Топ на одно плечо/021.webp",
    "portfolio/img/Топ на одно плечо/022.webp",
    "portfolio/img/Топ на одно плечо/023.webp",
    "portfolio/img/Топ на одно плечо/024.webp",
    "portfolio/img/Топ на одно плечо/025.webp",
    "portfolio/img/Топ на одно плечо/026.webp",
    "portfolio/img/Топ на одно плечо/027.webp",
    "portfolio/img/Топ на одно плечо/028.webp",
    "portfolio/img/Топ на одно плечо/029.webp",
    "portfolio/img/Топ на одно плечо/030.webp",
    "portfolio/img/Топ на одно плечо/031.webp",
    "portfolio/img/Топ на одно плечо/032.webp",
    "portfolio/img/Топ на одно плечо/033.webp",
    "portfolio/img/Топ на одно плечо/034.webp",
    "portfolio/img/Топ на одно плечо/035.webp",
    "portfolio/img/Топ на одно плечо/036.webp",
    "portfolio/img/Топ на одно плечо/037.webp",
    "portfolio/img/Топ на одно плечо/038.webp",
    "portfolio/img/Топ на одно плечо/039.webp",
    "portfolio/img/Топ на одно плечо/040.webp",
    "portfolio/img/Топ на одно плечо/041.webp",
    "portfolio/img/Топ на одно плечо/042.webp",
    "portfolio/img/Топ на одно плечо/043.webp",
    "portfolio/img/Топ на одно плечо/044.webp",
    "portfolio/img/Топ на одно плечо/045.webp",
    "portfolio/img/Топ на одно плечо/046.webp",
    "portfolio/img/Топ на одно плечо/047.webp",
    "portfolio/img/Топ на одно плечо/048.webp",
    "portfolio/img/Топ на одно плечо/049.webp",
    "portfolio/img/Топ на одно плечо/050.webp",
    "portfolio/img/Топ на одно плечо/051.webp",
    "portfolio/img/Топ на одно плечо/052.webp",
    "portfolio/img/Топ на одно плечо/053.webp",
    "portfolio/img/Топ на одно плечо/054.webp",
    "portfolio/img/Топ на одно плечо/055.webp",
    "portfolio/img/Топ на одно плечо/056.webp"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "futbolka-oversize-udlinennaya",
    ru: { title: "Футболка Oversize удлиненная", desc: "" },
    en: { title: "Extended Oversize T-shirt", desc: "" },
    zh: { title: "加长Oversize T恤", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Футболка _Oversize_ удлиненная/01.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/02.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/03.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/04.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/05.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/06.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/07.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/08.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/09.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/010.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/011.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/012.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/013.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/014.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/015.jpg",
    "portfolio/img/Футболка _Oversize_ удлиненная/016.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "futbolka-oversize-ukorochennaya",
    ru: { title: "Футболка Oversize укороченная", desc: "" },
    en: { title: "Cropped Oversize T-shirt", desc: "" },
    zh: { title: "短款Oversize T恤", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Футболка _Oversize_ укороченная/01.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/02.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/03.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/04.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/05.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/06.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/07.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/08.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/09.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/010.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/011.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/012.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/013.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/014.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/015.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/016.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/017.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/018.jpg",
    "portfolio/img/Футболка _Oversize_ укороченная/019.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  },
  {
    id: "shtany-kargo",
    ru: { title: "Штаны Карго", desc: "" },
    en: { title: "Cargo Pants", desc: "" },
    zh: { title: "工装裤", desc: "" },
    tags: ["одежда"],
    tags_en: ["clothing"],
    tags_zh: ["服装"],
    photos: [
    "portfolio/img/Штаны _Карго_/01.jpg",
    "portfolio/img/Штаны _Карго_/02.jpg",
    "portfolio/img/Штаны _Карго_/03.jpg",
    "portfolio/img/Штаны _Карго_/04.jpg",
    "portfolio/img/Штаны _Карго_/05.jpg",
    "portfolio/img/Штаны _Карго_/06.jpg",
    "portfolio/img/Штаны _Карго_/07.jpg",
    "portfolio/img/Штаны _Карго_/08.jpg",
    "portfolio/img/Штаны _Карго_/09.jpg",
    "portfolio/img/Штаны _Карго_/010.jpg",
    "portfolio/img/Штаны _Карго_/011.jpg",
    "portfolio/img/Штаны _Карго_/012.jpg",
    "portfolio/img/Штаны _Карго_/013.jpg",
    "portfolio/img/Штаны _Карго_/014.jpg",
    "portfolio/img/Штаны _Карго_/015.jpg",
    "portfolio/img/Штаны _Карго_/016.jpg",
    "portfolio/img/Штаны _Карго_/017.jpg",
    "portfolio/img/Штаны _Карго_/018.jpg",
    "portfolio/img/Штаны _Карго_/019.jpg",
    "portfolio/img/Штаны _Карго_/020.jpg",
    "portfolio/img/Штаны _Карго_/021.jpg",
    "portfolio/img/Штаны _Карго_/022.jpg",
    "portfolio/img/Штаны _Карго_/023.jpg"
    ],
    year: "2024",
    client: "",
    services_ru: ["Лекала", "Дизайн"],
    services_en: ["Pattern Making", "Design"],
    services_zh: ["制版", "设计"],
  }
];
